### ISSUE TITLE
Continuation of the project

### ISSUE THREAD

**Issue by patriciabt** [lupoair/caneveryoneuse#43]
Hello everyone!

Please tell us below if you are interested to continue to work on the project!
We are a great team and it was wonderful to be together on the project at the Hackathon!

Just a simple yes/no is good
Check the currently tasks assigned to you, incl translations, and do not hesitate to create new tasks

Looking forward to reading you

**Comment by patriciabt** [comment]
@Bovelett @bgonzalez @lupoair 
@Andir16 @carolili @dhanukanuwan @NinaJam @Oezhan @PatrickKoppe4fb @Stefan0x @Tanya-Val @tstauer 
Did I forget anyone? 

Just tell us if you want to continue or not. Thanks!

**Comment by NinaJam** [comment]
Tobias (new to the club) and I would like to take part. We would like to take over the UI / UX for the website. I think it would be good if we discussed the technologies again, what do you think?

**Comment by patriciabt** [comment]
Welcome to Tobias!
Thank you @NinaJam. Do you think we should have a call with a few of us? @Bovelett and others?
I could schedule that for next week or the week after

**Comment by NinaJam** [comment]
Good idea, for us, the 10.04 in the morning or on the 17 in the afternoon fits. Is that possible?

**Comment by patriciabt** [comment]
Let's wait and see what fits best the majority but yeah, let's aim for the 10th April in the morning
Thanks a lot

**Comment by bgonzalez** [comment]
Please wait for the following week.
The 10th and 11th you might want to attend this event:
https://www.accessibilityassociation.org/s/iaap-eu-event-2024



-- Beatriz Gonzalez Mellidez

**Comment by patriciabt** [comment]
Thank you @bgonzalez 
So we schedule for 17 in afternoon? (CET)

**Comment by bgonzalez** [comment]
Wednesday 17th in the afternoon (17h?), I am in!
Next week Wednesday at 17h I’m not 😅

-- Beatriz Gonzalez Mellidez

**Comment by Bovelett** [comment]
April 17, at 17:00 works for me too! :-)

**Comment by Tanya-Val** [comment]
Hello, can I join as well? :)

**Comment by Andir16** [comment]
I could imagine continuing, but I was thinking more about automating the component testing. One idea would be to crawl (regularly) the different libraries and create our own overview page, where we can then test the components automatically. 

Unfortunately, I won't be able to work on that until the middle of July (at the earliest) as I am preoccupied with work and other obligations. But this is also not one of the most pressing things, I think, as we already have an initial overview, and further libraries could still be evaluated manually for now.

**Comment by bgonzalez** [comment]
I can have a chat with accessibility cloud

Even without the chat, there is a free plan with 1site, 1user, 5 sites and
5 documents.
So if we crawl the components and create 5 library pages, we could make the
automated part work.

If we have more than 5 libraries I can gave the chat to see if there any
pricing in the middle for open source projects




-- Beatriz Gonzalez Mellidez

**Comment by bgonzalez** [comment]
We can also reference this

https://webaim.org/projects/million/#technologies

https://webaim.org/projects/million/#webframeworks


For those of you Wordpress & Joomla & typo 3 people :
https://webaim.org/projects/million/#CMS

-- Beatriz Gonzalez Mellidez

**Comment by patriciabt** [comment]
I created a calendar invite for 17 April at 17:00 CET
https://calendar.app.google/53JzGwaBfCorxutb9

https://yl.is/meeting/

As I do not have your email addresses, feel free to add yourself

The "Butter" video tool: you do not need to download their app, you can join via your browser (chrome based preferred)

**Comment by patriciabt** [comment]
@Andir16 and @bgonzalez can you create separate tickets to reference those you mentioned above
- automating the component testing
- accessibility cloud
- WebAIM

Also, Beatriz, as you reply by email, it looks like it adds the whole email to your comment :)

Thanks a lot!

**Comment by dhanukanuwan** [comment]
@patriciabt I also would like to continue working on the project. I can start working a few hours a month from the start of May. I would like to keep working on the tool.

**Comment by Andir16** [comment]
> @Andir16 and @bgonzalez can you create separate tickets to reference those you mentioned above
> 
> * automating the component testing
> * accessibility cloud
> * WebAIM
> 
> Also, Beatriz, as you reply by email, it looks like it adds the whole email to your comment :)
> 
> Thanks a lot!

Created a ticket (#45) for the automation of the testing of the components.
